### ISSUE TITLE
Svelte is not a disappearing framework

### ISSUE THREAD

**Issue by joas8211** [plentico/plenti.co#12]
> All the templating is done in the "disappearing" JS component framework called Svelte.
> \- https://plenti.co/docs/layouts

Svelte is not a disappearing framework, the popularity seems quite oppositely be rising, although quite low compared to the popular framework such as Vue.js and ReactJS. It is not disappearing.

**Comment by jimafisk** [comment]
That phrase is probably worth changing in the docs, but it was not intended to refer to Svelte's popularity, which is definitely rising. Svelte v2 used to brand itself as a "disappearing UI framework" (https://v2.svelte.dev/) since it [compiles itself out](https://ryansolid.medium.com/svelte-was-originally-promoted-as-the-disappearing-framework-since-it-compiled-out-the-framework-e0d8470dec2c) of the code shipped to the browser. Good call though, I'll update this since I don't really see than saying this much anymore. Thanks!

**Comment by joas8211** [comment]
I started with Svelte v3 so I didn't know the actual meaning of this phrase. Probably good that Svelte has changed brand to be honest. Disappering framework doesn't seem appealing :smile:
